# Generated by Django 4.2.16 on 2025-07-29 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='article',
            new_name='news_articl_created_a034b3_idx',
            old_name='news_article_created_09dd1c_idx',
        ),
        migrations.RenameIndex(
            model_name='article',
            new_name='news_articl_status_a95c4c_idx',
            old_name='news_article_status_5a8dd0_idx',
        ),
    ]
